name: "pre_LSTM_ka_s"

data:
    src: "tr_s"
    trg: "en_s"
    train: "../2DL4NLP/all_data/tr_s.en_s/train.bpe"
    dev: "../2DL4NLP/all_data/tr_s.en_s/val.bpe"
    test: "../2DL4NLP/all_data/tr_s.en_s/test.bpe"
    level: "bpe"
    lowercase: False
    max_sent_length: 50
    src_voc_min_freq: 0
    src_voc_limit: 100000
    trg_voc_min_freq: 0
    trg_voc_limit: 100000
    src_vocab: "../2DL4NLP/all_data/tr_s.en_s/tr_s.en_s.vocab.txt"
    trg_vocab: "../2DL4NLP/all_data/tr_s.en_s/tr_s.en_s.vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0

training:
    load_model: "../checkpoints/LSTM_ka.ckpt"
    reset_best_ckpt: True
    reset_iter_state: True
    random_seed: 42
    optimizer: "adam"
    learning_rate: 0.0003
    learning_rate_min: 0.0000005
    weight_decay: 0.0
    clip_grad_norm: 1.0
    batch_size: 80
    scheduling: "plateau"
    patience: 10
    decrease_factor: 0.5
    early_stopping_metric: "eval_metric"
    epochs: 20
    validation_freq: 100
    logging_freq: 1000
    eval_metric: "bleu"
    model_dir: "models/pre_LSTM_ka_s"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2]
    keep_best_ckpts: 1
    save_latest_ckpt: True

model:
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 512
        bidirectional: False
        dropout: 0.2
        num_layers: 1
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 1024
        dropout: 0.2
        hidden_dropout: 0.2
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
